kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: chrispruitt/drone-ecr-registry-plugin
    squash: true
    auto_tag: true
    cache_from:
      - "chrispruitt/drone-ecr-registry-plugin:latest"

